[workspace]
members = ["bittorrent-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Johannes <thexydez@gmail.com>"]

[workspace.dependencies]
log = "0.4"
tokio = "1.19"

[package]
name = "bittorrent"
description = "lightweight implementation of the bittorrent v1 protocol"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[features]
io-tests = []
net-tests = []

[dependencies]
bytes = "1.2.1"
lazy_static = "1.4.0"
percent-encoding = "2.1"
rand = "0.8.5"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_json = "1.0"
sha-1 = "0.10"
tap = "1.0.1"
thiserror = "1.0"
log = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
paste = "1.0"
