[package]
name = "bittorrent"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = "2.1.0"
reqwest = "0.11.4"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2.3"
serde_bytes = "0.11.5"
sha-1 = "0.9.7"
tokio = { version = "1.10.0", features = ["rt", "macros"] }

[features]
network-tests = []
