[package]
name = "bittorrent"
version = "0.1.0"
edition = "2018"

[dependencies]
num_cpus = "1.13"
percent-encoding = "2.1"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
sha-1 = "0.9"
futures = "0.3"
tokio = { version = "1.15", features = ["rt", "macros"] }

[features]
network-tests = []
