[package]
name = "bittorrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
log = "0.4"
percent-encoding = "2.1"
pretty_env_logger = "0.4"
rand = "0.8.5"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
sha-1 = "0.10"
strum = { version = "0.24", features = ["derive"] }
tap = "1.0.1"
tokio = { version = "1.19", features = ["rt", "macros"] }
