[workspace]
members = ["bittorrent-cli"] # "bittorrent-webui"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Johannes <thexydez@gmail.com>"]

[workspace.dependencies]
log = "0.4"
tokio = "1.22"

[package]
name = "bittorrent"
description = "lightweight implementation of the bittorrent v1 protocol"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[features]
default = ["resume"]
io-tests = []
net-tests = []
resume = ["bincode"]

[dependencies]
# Crate dependencies
bincode = { version = "1.3.3", optional = true }
bytes = "1.3"
lazy_static = "1.4"
paste = "1.0"
percent-encoding = "2.2"
rand = "0.8"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_json = "1.0"
sha1 = "0.10"
tap = "1.0"
thiserror = "1.0"
tokio-util = { version = "0.7.4", features = ["rt"] }

# Workspace dependencies
log = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
