[package]
name = "bittorrent"
version = "0.1.0"
edition = "2021"

[features]
io-tests = []
net-tests = []

[dependencies]
bytes = "1.2.1"
flexi_logger = "0.24"
lazy_static = "1.4.0"
log = "0.4"
percent-encoding = "2.1"
rand = "0.8.5"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
sha-1 = "0.10"
tap = "1.0.1"
thiserror = "1.0"
tokio = { version = "1.19", features = ["rt", "macros"] }
